"""Sensor platform for EcoFlow Cloud."""
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    PERCENTAGE,
    EntityCategory,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfTime,
    SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN, MANUFACTURER
from .coordinator import EcoflowCoordinator
from .devices.delta3_1500 import (
    DEVICE_MODEL,
    # Battery
    KEY_SOC, KEY_SOH, KEY_CYCLES,
    KEY_BATT_VOLT, KEY_BATT_CURR, KEY_BATT_TEMP,
    KEY_REMAIN_CAP, KEY_FULL_CAP, KEY_DESIGN_CAP,
    KEY_MIN_CELL_TEMP, KEY_MAX_CELL_TEMP,
    KEY_MIN_CELL_VOLT, KEY_MAX_CELL_VOLT,
    KEY_MIN_MOS_TEMP, KEY_MAX_MOS_TEMP,
    KEY_SOC_FLOAT, KEY_MAX_VOL_DIFF, KEY_DC12V_STATE,
    # BMS extended (v0.2.23)
    KEY_BMS_ACT_SOC, KEY_BMS_SOC, KEY_BMS_CHG_STATE, KEY_BMS_SYS_STATE,
    KEY_BMS_MOS_STATE, KEY_BMS_FAULT, KEY_BMS_ALL_FAULT,
    KEY_BMS_ERR_CODE, KEY_BMS_ALL_ERR, KEY_BMS_BALANCE,
    KEY_BMS_CHG_CAP, KEY_BMS_DSG_CAP, KEY_BMS_INPUT_W, KEY_BMS_OUTPUT_W,
    KEY_BMS_REAL_SOH, KEY_BMS_CALC_SOH, KEY_BMS_CYC_SOH,
    KEY_BMS_DIFF_SOC, KEY_BMS_TARGET_SOC, KEY_BMS_TAG_AMP,
    KEY_BMS_REMAIN_T, KEY_BMS_BQ_REG,
    # BmsInfo lifetime (v0.2.23)
    KEY_INFO_HIGH_T_CHG, KEY_INFO_HIGH_T, KEY_INFO_LOW_T_CHG, KEY_INFO_LOW_T,
    KEY_INFO_PWR_CAP,
    # EMS
    KEY_REMAIN_TIME, KEY_CHARGE_TIME,
    KEY_EMS_MAX_CHG_SOC, KEY_EMS_MIN_DSG_SOC,
    KEY_EMS_CHG_VOL, KEY_EMS_CHG_AMP, KEY_EMS_FAN_LEVEL,
    KEY_EMS_CHG_LINE, KEY_EMS_SYS_STATE,
    # EMS extended (v0.2.23)
    KEY_EMS_DSG_TIME, KEY_EMS_CHG_STATE, KEY_EMS_CHG_CMD, KEY_EMS_DSG_CMD,
    KEY_EMS_CHG_COND, KEY_EMS_DSG_COND, KEY_EMS_WARN, KEY_EMS_NORMAL,
    KEY_EMS_SOC_FLOAT, KEY_EMS_SOC_LCD, KEY_EMS_PARA_V_MAX, KEY_EMS_PARA_V_MIN,
    # Kit
    KEY_KIT_WATTS, KEY_KIT_NUM,
    # BmsInfo lifetime
    KEY_INFO_SOH, KEY_INFO_CYCLES,
    KEY_INFO_ACCU_CHG, KEY_INFO_ACCU_DSG,
    KEY_INFO_ACCU_CHG_E, KEY_INFO_ACCU_DSG_E,
    KEY_INFO_ROUND_TRIP, KEY_INFO_SELF_DSG,
    KEY_INFO_DEEP_DSG, KEY_INFO_OHM_RES,
    # AC / Inverter
    KEY_AC_OUT_W, KEY_AC_IN_W,
    KEY_AC_IN_VOLT, KEY_AC_IN_AMP, KEY_AC_IN_FREQ,
    KEY_AC_OUT_VOLT, KEY_AC_OUT_AMP, KEY_AC_OUT_FREQ_RT,
    KEY_AC_FAST_CHG_W, KEY_AC_SLOW_CHG_W,
    KEY_AC_TEMP, KEY_AC_FAN_STATE,
    KEY_DC_IN_VOLT, KEY_DC_IN_AMP, KEY_DC_IN_TEMP, KEY_AC_CFG_FREQ,
    # INV extended (v0.2.23)
    KEY_INV_WORK_MODE, KEY_INV_CHARGER_T, KEY_INV_DSG_TYPE,
    KEY_INV_ERR_CODE, KEY_INV_DIP,
    # Solar / MPPT
    KEY_SOLAR_W, KEY_SOLAR_VOLT, KEY_SOLAR_AMP,
    KEY_SOLAR_OUT_W, KEY_MPPT_TEMP,
    KEY_DC12V_OUT_W, KEY_DC12V_OUT_VOLT, KEY_DC12V_OUT_AMP,
    KEY_DC12V_TEMP, KEY_DC12V_IN_W, KEY_DC_OUT_TEMP, KEY_DCDC12V_W,
    # MPPT extended (v0.2.23)
    KEY_MPPT_CHG_STATE, KEY_MPPT_CHG_TYPE, KEY_MPPT_CFG_CHG_T,
    KEY_MPPT_DSG_TYPE, KEY_MPPT_FAULT, KEY_MPPT_OUT_AMP, KEY_MPPT_OUT_VOLT,
    KEY_MPPT_DC24V_ST, KEY_SCR_STANDBY, KEY_POW_STANDBY,
    # USB
    KEY_USB1_W, KEY_USB2_W, KEY_USB_QC1_W, KEY_USB_QC2_W,
    KEY_USBC1_W, KEY_USBC2_W,
    KEY_USBC1_TEMP, KEY_USBC2_TEMP,
    # PD / System
    KEY_IN_W_TOTAL, KEY_OUT_W_TOTAL,
    KEY_CHG_POWER_AC, KEY_CHG_POWER_DC,
    KEY_DSG_POWER_AC, KEY_DSG_POWER_DC,
    KEY_CHG_SUN_POWER, KEY_WIFI_RSSI,
    KEY_BP_POWER_SOC, KEY_GEN_MIN_SOC, KEY_GEN_MAX_SOC, KEY_MPPT_BEEP,
    # PD extended (v0.2.23)
    KEY_PD_CAR_TEMP, KEY_PD_CAR_TIME, KEY_PD_CHG_TYPE, KEY_PD_DCIN_TIME,
    KEY_PD_ERR_CODE, KEY_PD_RJ45, KEY_PD_EXT38, KEY_PD_EXT48,
    KEY_PD_HYSTERESIS, KEY_PD_INV_TIME, KEY_PD_MPPT_TIME, KEY_PD_RELAY_CNT,
    KEY_PD_TYPEC_TIME, KEY_PD_USB_TIME, KEY_PD_USBQC_TIME, KEY_PD_WIFI_RCV,
    # Slave battery (v0.2.25)
    KEY_SLV_SOC, KEY_SLV_SOC_FLOAT, KEY_SLV_SOH, KEY_SLV_REAL_SOH,
    KEY_SLV_VOLT, KEY_SLV_CURR, KEY_SLV_TEMP,
    KEY_SLV_MIN_CELL_T, KEY_SLV_MAX_CELL_T,
    KEY_SLV_MIN_MOS_T, KEY_SLV_MAX_MOS_T,
    KEY_SLV_MIN_CELL_V, KEY_SLV_MAX_CELL_V, KEY_SLV_MAX_VOL_D,
    KEY_SLV_REMAIN_CAP, KEY_SLV_FULL_CAP, KEY_SLV_DESIGN_CAP,
    KEY_SLV_INPUT_W, KEY_SLV_OUTPUT_W, KEY_SLV_CYCLES, KEY_SLV_REMAIN_T,
    KEY_SLV_DIFF_SOC, KEY_SLV_CHG_CAP, KEY_SLV_DSG_CAP,
    KEY_SLV_ACCU_CHG, KEY_SLV_ACCU_DSG, KEY_SLV_ACCU_CHG_E, KEY_SLV_ACCU_DSG_E,
    KEY_SLV_OHM_RES, KEY_SLV_ROUND_TRIP, KEY_SLV_DEEP_DSG,
    KEY_SLV_ERR_CODE, KEY_SLV_CYC_SOH,
)

_LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True, kw_only=True)
class EcoFlowSensorDescription(SensorEntityDescription):
    """Sensor description with optional scaling and rounding."""
    scale:        float       = 1.0
    round_digits: int | None  = 2
    # Optional fallback key used when the primary key is absent in coordinator data
    fallback_key: str | None  = None


SENSOR_DESCRIPTIONS: tuple[EcoFlowSensorDescription, ...] = (

    # ── Battery ──────────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_SOC,
        name="Battery Level",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SOC_FLOAT,
        name="Battery Level (precise)",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SOH,
        name="State of Health (BMS Status)",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_CYCLES,
        name="Charge Cycles",
        icon="mdi:battery-sync",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_REMAIN_CAP,
        name="Remaining Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-medium",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_FULL_CAP,
        name="Full Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-high",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_DESIGN_CAP,
        name="Design Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_BATT_VOLT,
        name="Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_BATT_CURR,
        name="Battery Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_BATT_TEMP,
        name="Battery Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_MIN_CELL_TEMP,
        name="Min Cell Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MAX_CELL_TEMP,
        name="Max Cell Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MIN_MOS_TEMP,
        name="Min MOS Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_MAX_MOS_TEMP,
        name="Max MOS Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_MIN_CELL_VOLT,
        name="Min Cell Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MAX_CELL_VOLT,
        name="Max Cell Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MAX_VOL_DIFF,
        name="Max Cell Voltage Difference",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── EMS ──────────────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_REMAIN_TIME,
        name="Time Remaining",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer-outline",
        fallback_key="pd.remainTime",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_CHARGE_TIME,
        name="Time to Full",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:timer-plus-outline",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_MAX_CHG_SOC,
        name="Max Charge Level",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-arrow-up",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_MIN_DSG_SOC,
        name="Min Discharge Level",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-arrow-down",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_VOL,
        name="EMS Charge Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_AMP,
        name="EMS Charge Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_FAN_LEVEL,
        name="Fan Level",
        icon="mdi:fan",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_LINE,
        name="AC Plug Connected",
        icon="mdi:power-plug",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_SYS_STATE,
        name="System Charge/Discharge State",
        icon="mdi:battery-arrow-up-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── Extra battery kit ─────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_KIT_WATTS,
        name="Extra Battery Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:battery-plus",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_KIT_NUM,
        name="Extra Batteries Connected",
        icon="mdi:battery-plus-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── AC / Inverter ─────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_AC_OUT_W,
        name="AC Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:power-socket-eu",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_IN_W,
        name="AC Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:transmission-tower",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_IN_VOLT,
        name="AC Input Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_IN_AMP,
        name="AC Input Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_IN_FREQ,
        name="AC Input Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_OUT_VOLT,
        name="AC Output Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_OUT_AMP,
        name="AC Output Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_OUT_FREQ_RT,
        name="AC Output Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_CFG_FREQ,
        name="AC Configured Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_FAST_CHG_W,
        name="AC Fast Charge Watts",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_SLOW_CHG_W,
        name="AC Slow Charge Watts",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:flash-outline",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_AC_TEMP,
        name="Inverter Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC_IN_VOLT,
        name="Inverter DC Input Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        entity_registry_enabled_default=False,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC_IN_AMP,
        name="Inverter DC Input Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        entity_registry_enabled_default=False,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC_IN_TEMP,
        name="Inverter DC Input Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        round_digits=1,
    ),

    # ── Solar / MPPT ─────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_SOLAR_W,
        name="Solar Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SOLAR_VOLT,
        name="Solar Input Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_SOLAR_AMP,
        name="Solar Input Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SOLAR_OUT_W,
        name="MPPT Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-power-variant",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_TEMP,
        name="MPPT Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC12V_OUT_W,
        name="DC 12V Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-electric",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC12V_IN_W,
        name="DC 12V Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-arrow-right",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC12V_TEMP,
        name="DC 12V Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC12V_STATE,
        name="DC 12V Port State",
        icon="mdi:car-electric",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_DC_OUT_TEMP,
        name="DC Output Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_DCDC12V_W,
        name="MPPT DC Converter Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:car-battery",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── USB / PD ─────────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_IN_W_TOTAL,
        name="Total Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:arrow-collapse-down",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_OUT_W_TOTAL,
        name="Total Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:arrow-expand-up",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USB1_W,
        name="USB-A 1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USB2_W,
        name="USB-A 2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USB_QC1_W,
        name="USB-A QC 1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USB_QC2_W,
        name="USB-A QC 2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USBC1_W,
        name="USB-C 1 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USBC2_W,
        name="USB-C 2 Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:usb-c-port",
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_USBC1_TEMP,
        name="USB-C 1 Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_USBC2_TEMP,
        name="USB-C 2 Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),

    # ── Energy totals ─────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_CHG_POWER_AC,
        name="Cumulative AC Charged",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_CHG_POWER_DC,
        name="Cumulative DC Charged",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_CHG_SUN_POWER,
        name="Solar Charge Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:solar-panel",
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── System ───────────────────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_BP_POWER_SOC,
        name="Battery Protection SOC",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-lock",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_WIFI_RSSI,
        name="WiFi Signal",
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS_MILLIWATT,
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),

    # ── Battery lifetime statistics (bms_bmsInfo) ─────────────────────────
    EcoFlowSensorDescription(
        key=KEY_INFO_SOH,
        name="State of Health (BMS Info)",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart-variant",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_CYCLES,
        name="Total Charge Cycles",
        icon="mdi:battery-sync",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_ACCU_CHG,
        name="Cumulative Charged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-plus-variant",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_ACCU_DSG,
        name="Cumulative Discharged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-minus-variant",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_ACCU_CHG_E,
        name="Cumulative Charged Energy",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_ACCU_DSG_E,
        name="Cumulative Discharged Energy",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_ROUND_TRIP,
        name="Round-Trip Efficiency",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_SELF_DSG,
        name="Self-Discharge Rate",
        native_unit_of_measurement=f"{PERCENTAGE}/day",
        icon="mdi:battery-minus",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_DEEP_DSG,
        name="Deep Discharge Count",
        icon="mdi:battery-alert",
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=False,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_OHM_RES,
        name="Internal Resistance",
        native_unit_of_measurement="mΩ",
        icon="mdi:omega",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        round_digits=1,
    ),

    # ── Slave battery (bms_slave) — v0.2.25 ──────────────────────────────
    # P361Z1H4PGBR0251 slave confirmed present via MQTT telemetry (April 2026).
    # Primary sensors enabled by default; diagnostics disabled by default.

    EcoFlowSensorDescription(
        key=KEY_SLV_SOC,
        name="Slave Battery Level",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_SOC_FLOAT,
        name="Slave Battery Level (precise)",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_SOH,
        name="Slave State of Health",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_VOLT,
        name="Slave Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_CURR,
        name="Slave Battery Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.001,
        round_digits=2,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_TEMP,
        name="Slave Battery Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_REMAIN_CAP,
        name="Slave Remaining Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-medium",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_FULL_CAP,
        name="Slave Full Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-high",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_DESIGN_CAP,
        name="Slave Design Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_INPUT_W,
        name="Slave Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_OUTPUT_W,
        name="Slave Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_CYCLES,
        name="Slave Charge Cycles",
        icon="mdi:battery-sync",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_REMAIN_T,
        name="Slave Time Remaining",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    # Slave diagnostics
    EcoFlowSensorDescription(
        key=KEY_SLV_MIN_CELL_T,
        name="Slave Min Cell Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MAX_CELL_T,
        name="Slave Max Cell Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MIN_MOS_T,
        name="Slave Min MOS Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MAX_MOS_T,
        name="Slave Max MOS Temperature",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MIN_CELL_V,
        name="Slave Min Cell Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MAX_CELL_V,
        name="Slave Max Cell Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_MAX_VOL_D,
        name="Slave Max Cell Voltage Difference",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_REAL_SOH,
        name="Slave Real State of Health",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart-variant",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_CHG_CAP,
        name="Slave Charged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-plus",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_DSG_CAP,
        name="Slave Discharged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-minus",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ACCU_CHG,
        name="Slave Cumulative Charged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-plus-outline",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ACCU_DSG,
        name="Slave Cumulative Discharged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-minus-outline",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ACCU_CHG_E,
        name="Slave Cumulative Charged Energy",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ACCU_DSG_E,
        name="Slave Cumulative Discharged Energy",
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_OHM_RES,
        name="Slave Internal Resistance",
        native_unit_of_measurement="mOhm",
        icon="mdi:omega",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ROUND_TRIP,
        name="Slave Round-Trip Efficiency",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-sync-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_DEEP_DSG,
        name="Slave Deep Discharge Count",
        icon="mdi:battery-alert",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_ERR_CODE,
        name="Slave Error Code",
        icon="mdi:alert-circle-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_DIFF_SOC,
        name="Slave SOC Difference",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-arrow-up-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SLV_CYC_SOH,
        name="Slave Cycle State of Health",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),

    # ── Generator SOC thresholds (bms_emsStatus) ──────────────────────────
    EcoFlowSensorDescription(
        key=KEY_GEN_MIN_SOC,
        name="Generator Start SOC",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:engine-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_GEN_MAX_SOC,
        name="Generator Stop SOC",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:engine-off-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),

    # ── MPPT beep state ───────────────────────────────────────────────────

    # ── BMS extended diagnostics (v0.2.23) ───────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_BMS_ACT_SOC,
        name="Battery Actual SOC",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_SOC,
        name="Battery SOC (BMS)",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_CHG_STATE,
        name="BMS Charge State",
        icon="mdi:battery-charging",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_SYS_STATE,
        name="BMS System State",
        icon="mdi:information",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_MOS_STATE,
        name="BMS MOS State",
        icon="mdi:chip",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_FAULT,
        name="BMS Fault",
        icon="mdi:alert",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_ALL_FAULT,
        name="BMS All Faults",
        icon="mdi:alert",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_ERR_CODE,
        name="BMS Error Code",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_ALL_ERR,
        name="BMS All Error Codes",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_BALANCE,
        name="BMS Cell Balancing",
        icon="mdi:scale-balance",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_CHG_CAP,
        name="BMS Charged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-charging",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_DSG_CAP,
        name="BMS Discharged Capacity",
        native_unit_of_measurement="mAh",
        icon="mdi:battery-minus",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_INPUT_W,
        name="BMS Input Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_OUTPUT_W,
        name="BMS Output Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_REAL_SOH,
        name="BMS Real SoH",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_CALC_SOH,
        name="BMS Calculated SoH",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_CYC_SOH,
        name="BMS Cycle SoH",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-heart-variant",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_DIFF_SOC,
        name="BMS SOC Difference",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_TARGET_SOC,
        name="BMS Target SOC",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery-arrow-up",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=1,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_TAG_AMP,
        name="BMS Target Charge Current",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_REMAIN_T,
        name="BMS Remaining Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:clock",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_BMS_BQ_REG,
        name="BMS BQ Status Register",
        icon="mdi:chip",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    # BmsInfo lifetime (v0.2.23)
    EcoFlowSensorDescription(
        key=KEY_INFO_HIGH_T_CHG,
        name="High Temp Charge Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:thermometer-high",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_HIGH_T,
        name="High Temp Total Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:thermometer-high",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_LOW_T_CHG,
        name="Low Temp Charge Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:thermometer-low",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_LOW_T,
        name="Low Temp Total Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:thermometer-low",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INFO_PWR_CAP,
        name="Power Capability",
        icon="mdi:lightning-bolt",
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    # ── EMS extended (v0.2.23) ────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_EMS_DSG_TIME,
        name="Discharge Remaining Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:battery-clock",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_STATE,
        name="EMS Charge State",
        icon="mdi:battery-charging",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_CMD,
        name="EMS Charge Command",
        icon="mdi:battery-charging",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_DSG_CMD,
        name="EMS Discharge Command",
        icon="mdi:battery-minus",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_CHG_COND,
        name="EMS Charge Condition",
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_DSG_COND,
        name="EMS Discharge Condition",
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_WARN,
        name="EMS Warning State",
        icon="mdi:alert",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_NORMAL,
        name="EMS Normal Flag",
        icon="mdi:check-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_SOC_FLOAT,
        name="Display SOC (float)",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=2,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_SOC_LCD,
        name="Display SOC (LCD)",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_PARA_V_MAX,
        name="Parallel Voltage Max",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_EMS_PARA_V_MIN,
        name="Parallel Voltage Min",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    # ── INV extended (v0.2.23) ────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_INV_WORK_MODE,
        name="AC Work Mode",
        icon="mdi:power-settings",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INV_CHARGER_T,
        name="Charger Type (INV)",
        icon="mdi:ev-plug-type2",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INV_DSG_TYPE,
        name="Discharge Type",
        icon="mdi:battery-arrow-down",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INV_ERR_CODE,
        name="INV Error Code",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_INV_DIP,
        name="AC DIP Switch",
        icon="mdi:toggle-switch",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    # ── MPPT extended (v0.2.23) ───────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_MPPT_CHG_STATE,
        name="MPPT Charge State",
        icon="mdi:solar-power",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_CHG_TYPE,
        name="MPPT Charge Type",
        icon="mdi:ev-plug-type2",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_CFG_CHG_T,
        name="MPPT Configured Charge Type",
        icon="mdi:ev-plug-type2",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_DSG_TYPE,
        name="MPPT Discharge Type",
        icon="mdi:battery-arrow-down",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_FAULT,
        name="MPPT Fault Code",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_OUT_AMP,
        name="MPPT Output Current",
        native_unit_of_measurement=UnitOfElectricCurrent.MILLIAMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_OUT_VOLT,
        name="MPPT Output Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_DC24V_ST,
        name="DC 24V Port State",
        icon="mdi:power-socket",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_SCR_STANDBY,
        name="Screen Standby Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:monitor",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_POW_STANDBY,
        name="Overall Standby Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer-outline",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    # ── PD extended (v0.2.23) ─────────────────────────────────────────────
    EcoFlowSensorDescription(
        key=KEY_PD_CAR_TEMP,
        name="DC 12V Temperature (PD)",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_CAR_TIME,
        name="DC 12V Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_CHG_TYPE,
        name="Charger Type (PD)",
        icon="mdi:ev-plug-type2",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_DCIN_TIME,
        name="DC Input Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_ERR_CODE,
        name="PD Error Code",
        icon="mdi:alert-circle",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_RJ45,
        name="RJ45 Port Status",
        icon="mdi:ethernet",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_EXT38,
        name="3.8V Port Status",
        icon="mdi:power-socket",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_EXT48,
        name="4.8V Port Status",
        icon="mdi:power-socket",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_HYSTERESIS,
        name="Hysteresis SOC",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:battery",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_INV_TIME,
        name="Inverter Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_MPPT_TIME,
        name="MPPT Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_RELAY_CNT,
        name="Relay Switch Count",
        icon="mdi:counter",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_TYPEC_TIME,
        name="USB-C Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_USB_TIME,
        name="USB-A Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_USBQC_TIME,
        name="USB QC Use Time",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        icon="mdi:timer",
        state_class=SensorStateClass.TOTAL_INCREASING,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_PD_WIFI_RCV,
        name="WiFi Auto Recovery Mode",
        icon="mdi:wifi-sync",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
    EcoFlowSensorDescription(
        key=KEY_MPPT_BEEP,
        name="MPPT Beep",
        icon="mdi:volume-high",
        state_class=SensorStateClass.MEASUREMENT,
        round_digits=0,
        entity_registry_enabled_default=False,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up EcoFlow sensors from a config entry."""
    entry_data  = hass.data[DOMAIN][entry.entry_id]
    coordinator = entry_data["coordinator"]
    sn          = entry_data["sn"]

    entities: list = [
        EcoFlowSensorEntity(coordinator, desc, sn)
        for desc in SENSOR_DESCRIPTIONS
    ]
    # Diagnostic sensor — always added, shows connection mode in HA UI
    entities.append(EcoFlowConnectionModeSensor(entry_data, sn))
    async_add_entities(entities)


class EcoFlowSensorEntity(CoordinatorEntity[EcoflowCoordinator], SensorEntity):
    """One sensor backed by the EcoFlow coordinator."""

    entity_description: EcoFlowSensorDescription

    def __init__(
        self,
        coordinator: EcoflowCoordinator,
        description: EcoFlowSensorDescription,
        sn: str,
    ) -> None:
        super().__init__(coordinator)
        self.entity_description  = description
        self._sn                 = sn
        self._attr_unique_id     = f"{sn}_{description.key}"
        self._attr_has_entity_name = True
        self._attr_device_info   = DeviceInfo(
            identifiers={(DOMAIN, sn)},
            name=f"EcoFlow {DEVICE_MODEL}",
            manufacturer=MANUFACTURER,
            model=DEVICE_MODEL,
        )

    @property
    def native_value(self) -> float | str | None:
        if not self.coordinator.data:
            return None
        val = self.coordinator.data.get(self.entity_description.key)
        # Fall back to secondary key when primary is absent or zero
        if (val is None or val == 0) and self.entity_description.fallback_key:
            val = self.coordinator.data.get(self.entity_description.fallback_key)
        if val is None:
            return None
        try:
            scaled = float(val) * self.entity_description.scale
            r = self.entity_description.round_digits
            return round(scaled, r) if r is not None else scaled
        except (TypeError, ValueError):
            return str(val)

    @property
    def available(self) -> bool:
        return bool(self.coordinator.data)


class EcoFlowConnectionModeSensor(SensorEntity):
    """Diagnostic sensor showing the active connection mode.

    Values:
      hybrid    — MQTT telemetry (Private API) + REST SET (Developer API)
      mqtt_only — MQTT telemetry only, REST SET unavailable
      rest_only — Developer API only (no MQTT / fallback)

    Always enabled regardless of coordinator data — useful for diagnosing
    setup problems before any telemetry arrives.
    """

    _attr_has_entity_name                 = True
    _attr_entity_registry_enabled_default = True
    _attr_icon                            = "mdi:connection"
    _attr_entity_category                 = EntityCategory.DIAGNOSTIC

    def __init__(self, entry_data: dict, sn: str) -> None:
        self._entry_data       = entry_data
        self._sn               = sn
        self._attr_unique_id   = f"{sn}_connection_mode"
        self._attr_name        = "Connection Mode"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, sn)},
            name=f"EcoFlow {DEVICE_MODEL}",
            manufacturer=MANUFACTURER,
            model=DEVICE_MODEL,
        )

    @property
    def native_value(self) -> str:
        """Return active connection mode string."""
        has_mqtt = self._entry_data.get("mqtt_client") is not None
        has_rest = self._entry_data.get("rest_api") is not None
        if has_mqtt and has_rest:
            return "hybrid"
        if has_mqtt:
            return "mqtt_only"
        return "rest_only"

    @property
    def extra_state_attributes(self) -> dict:
        """Extra diagnostic detail visible in HA developer tools."""
        has_rest   = self._entry_data.get("rest_api") is not None
        has_mqtt   = self._entry_data.get("mqtt_client") is not None
        api        = self._entry_data.get("api")
        is_private = hasattr(api, "_email")
        return {
            "mqtt_connected":    has_mqtt,
            "rest_api_attached": has_rest,
            "auth_mode":         "private" if is_private else "public",
            "sn":                self._sn,
        }

    @property
    def available(self) -> bool:
        return True  # always available — diagnostic sensor
